name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test_dotnet:
    name: Build and Test .NET
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  build_and_test_nodejs:
    name: Build and Test NodeJS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PollMeWeb
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Verify Chromium Installation
      run: chromium-browser --version
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm test
